### Problem Statement :- Predict the Sales prices

In [12]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
import matplotlib.pyplot 
import seaborn as sns

--------------------------------------------------------------------

### Data science Stage 2 :- Data Collection ( stage 1 is understanding the problem / need / requirement )

In [2]:
train_data = pd.read_csv("train.csv")

train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

------------------------------------------------------------------------------------------


### Data Science Stage 3 :- Data Preprocessing ( i am taking the liberty of adding data cleaning in this stage )

In [3]:
train_data = train_data.ffill() # imputation method for train dataset

In [4]:
x = train_data.bfill()

x

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Grvl,Reg,Lvl,AllPub,...,0,Ex,MnPrv,Shed,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Grvl,Reg,Lvl,AllPub,...,0,Ex,MnPrv,Shed,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Grvl,IR1,Lvl,AllPub,...,0,Ex,MnPrv,Shed,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Grvl,IR1,Lvl,AllPub,...,0,Ex,MnPrv,Shed,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Grvl,IR1,Lvl,AllPub,...,0,Ex,MnPrv,Shed,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Pave,Reg,Lvl,AllPub,...,0,Gd,GdWo,TenC,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Pave,Reg,Lvl,AllPub,...,0,Gd,MnPrv,TenC,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Pave,Reg,Lvl,AllPub,...,0,Gd,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Pave,Reg,Lvl,AllPub,...,0,Gd,GdPrv,Shed,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Pave,Reg,Lvl,AllPub,...,0,Gd,GdPrv,Shed,0,6,2008,WD,Normal,147500

In [5]:
test_data = pd.read_csv("test.csv")

test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [6]:
test_data = test_data.ffill() # imputation method for test dataset

In [7]:
y = test_data.bfill()

y

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Pave,Reg,Lvl,AllPub,...,120,0,Ex,MnPrv,Gar2,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,Pave,IR1,Lvl,AllPub,...,0,0,Ex,MnPrv,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,Pave,IR1,Lvl,AllPub,...,0,0,Ex,MnPrv,Gar2,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,Pave,IR1,Lvl,AllPub,...,0,0,Ex,MnPrv,Gar2,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,Pave,IR1,HLS,AllPub,...,144,0,Ex,MnPrv,Gar2,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,Gd,GdPrv,Shed,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,Gd,GdPrv,Shed,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,Gd,GdPrv,Shed,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,Gd,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,Gd,MnPrv,Shed,0,11,2006,WD,Normal

In [9]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1460 non-null   object
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1460 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1460 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

### Given below is the Encoding for categorical varaibles ( 43 )  for building a predictive model

### Train Dataset Encoding

In [10]:
cat_col = x.select_dtypes(include=['object']).columns

enco = OneHotEncoder(drop='first',sparse_output=False ,handle_unknown ='ignore')

encoded_data = enco.fit_transform(x[cat_col])

encoded_columns = enco.get_feature_names_out(cat_col)

cat_encoded_data = pd.DataFrame(encoded_data,columns = encoded_columns,index = x.index)

x_encoded = x.drop(columns=cat_col)

x_encoded = pd.concat([x_encoded,cat_encoded_data], axis=1)

print(x_encoded.info())

print(x_encoded.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 246 entries, Id to SaleCondition_Partial
dtypes: float64(211), int64(35)
memory usage: 2.7 MB
None
   Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0   1          60         65.0     8450            7            5       2003
1   2          20         80.0     9600            6            8       1976
2   3          60         68.0    11250            7            5       2001
3   4          70         60.0     9550            7            5       1915
4   5          60         84.0    14260            8            5       2000

   YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  SaleType_ConLI  SaleType_ConLw  \
0          2003       196.0         706  ...             0.0             0.0
1          1976         0.0         978  ...             0.0             0.0
2          2002       162.0         486  ...             0.0             0.0
3          1970         0.0         216  ...             0.0             0.0
4          2000       350.0         655  ...             0.0             0.0

   SaleType_New  SaleType_Oth  SaleType_WD  SaleCondition_AdjLand  \
0           0.0           0.0          1.0                    0.0
1           0.0           0.0          1.0                    0.0
2           0.0           0.0          1.0                    0.0
3           0.0           0.0          1.0                    0.0
4           0.0           0.0          1.0                    0.0

   SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                   0.0                   0.0                   1.0
1                   0.0                   0.0                   1.0
2                   0.0                   0.0                   1.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   1.0

   SaleCondition_Partial
0                    0.0
1                    0.0
2                    0.0
3                    0.0
4                    0.0

[5 rows x 246 columns]

In [13]:
x_encoded # this is the encoded full training dataset

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [14]:
x_encoded.drop_duplicates() ## remember to drop the duplicates next time

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Test Dataset Encoding

In [15]:
categorical_encoding = y.select_dtypes(include=['object']).columns

test_encoding = enco.fit_transform(y[categorical_encoding])

test_encoded_columns = enco.get_feature_names_out(categorical_encoding)

test_encoded_data = pd.DataFrame(test_encoding,columns=test_encoded_columns, index=y.index)

y_encoded = y.drop(columns=categorical_encoding)

y_encoded = pd.concat([y_encoded,test_encoded_data],axis =1)

In [18]:
y_encoded.info()
y_encoded.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 227 entries, Id to SaleCondition_Partial
dtypes: float64(201), int64(26)
memory usage: 2.5 MB

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

## Note :- Remember that feature scaling is usefull for caluculating the distance based models everytime even if the data is equal tailed you still need to look at features such as salary / price which might be over shawdowing another feature such as age then we need to scale so that it doesnt produce biased model , but feature scaling is not required for tree based models because its not distance based models

#### we will be working on eda now as standard scaling the dataset would not predict the price , not viable

-------------------------------------------------------

### Data Science Stage 4 :- EDA

In [32]:
x.describe() # i chose the train data because it has the values that we need without the data encoding therefore it gives us the story of whats going on

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.104795,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.492466,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,23.846996,9981.264932,1.382997,1.112799,30.202904,20.645407,180.795612,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,70.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,165.250000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

## Observations

### 1 . The average condition of houses in iowa is 5 with the average quality of 6 and the average year at which the houses were built was 1971 and the average year of remodeling was in 1984 with average houses sold in the year of 2007 in the month of august with a average sale price of 180k$

### 2 . The minimum amount sales done in iowa was in the the 2006 , with lowest sale record going in the month of jan , the oldest house built in iowa was in 1872 & oldest remodelling done was in 1950 , the lowest sale is 34k$

### 3. The lowest overall condition is 1 , with lowest quality at 1 , while the highest condition is at 9 and highest overall condition is at 10 , the most recent house built was in year 2010 with the latest remodelling done in 2010 , while the highest selling house was worth money 755,000 $

### therefore these are primary observations i could draw , and there are factors that depeict the price of the sale now lets look towards the features

In [33]:
x_encoded.skew()

Id                        0.000000
MSSubClass                1.407657
LotFrontage               1.953095
LotArea                  12.207688
OverallQual               0.216944
                           ...
SaleCondition_AdjLand    19.045943
SaleCondition_Alloca     10.905010
SaleCondition_Family      8.376038
SaleCondition_Normal     -1.672412
SaleCondition_Partial     2.965079
Length: 246, dtype: float64

In [34]:
x_encoded.kurtosis()

Id                        -1.200000
MSSubClass                 1.580188
LotFrontage               15.598415
LotArea                  203.243271
OverallQual                0.096293
                            ...
SaleCondition_AdjLand    361.242801
SaleCondition_Alloca     117.079634
SaleCondition_Family      68.251510
SaleCondition_Normal       0.798054
SaleCondition_Partial      6.801009
Length: 246, dtype: float64

In [66]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [67]:
model = LinearRegression()

xx = x_encoded.drop(columns=['SalePrice'])
yy = x_encoded['SalePrice']



x_train , x_test , y_train , y_test = train_test_split(xx,yy,test_size=0.2,random_state = 42)

y_train = np.log1p(y_train)


model.fit(x_train,y_train)

LinearRegression()

In [68]:
# Find missing columns in test dataset
missing_cols = set(x_train.columns) - set(y_encoded.columns)
extra_cols = set(y_encoded.columns) - set(x_train.columns)

print(f"Missing in test: {missing_cols}")
print(f"Extra in test: {extra_cols}")

Missing in test: set()
Extra in test: set()

In [69]:
# Ensure all missing columns are added to test data
for col in missing_cols:
    y_encoded[col] = 0  # Add missing columns with 0 values

# Ensure the column order is the same
y_encoded = y_encoded[x_train.columns]

In [75]:
y_pred = model.predict(x_test)

y_pred_log = np.expm1(y_pred)

In [76]:
y_pred

array([11.94620723, 12.77126253, 11.49253906, 12.02793782, 12.67104581,
       11.29039114, 12.4126808 , 11.91113802, 11.25237657, 11.85709554,
       11.88115835, 11.67793021, 11.27945754, 12.28385833, 12.0942312 ,
       11.8056332 , 12.14997761, 11.82025686, 11.58727253, 12.27404163,
       11.97442122, 12.24035865, 12.06906808, 11.81117741, 12.20651254,
       11.91426891, 12.15813999, 11.58587996, 12.10183845, 12.16157642,
       12.04367383, 12.53631818, 12.25050308, 11.65888493, 12.45786225,
       11.91587813, 11.90463891, 12.18184105, 12.69175001, 11.58102654,
       11.81625195, 12.32267898, 11.59441724, 12.83538842, 11.76110411,
       11.76973178, 11.55976004, 11.80879503, 13.06652702, 11.82901536,
       11.67811101, 12.27210842, 11.55195296, 12.64546361, 12.03499257,
       12.36152832, 12.20504004, 11.97100771, 11.77488757, 11.37416594,
       11.29299199, 11.98573686, 12.652897  , 12.40851495, 12.57284047,
       12.18180924, 11.6169345 , 12.68057619, 11.79640895, 12.06509875,
       11.71079213, 11.72237771, 11.62427155, 11.21058536, 13.1384642 ,
       12.11418552, 12.64380317, 12.67284538, 11.91829617, 11.72139125,
       11.63164487, 11.37543569, 11.63627837, 11.5276498 , 11.95768284,
       11.7955002 , 12.50647546, 12.13940399, 11.86436007, 12.12276101,
       11.89588256, 11.87856373, 11.78228501, 12.525696  , 11.61488438,
       12.11268871, 12.04052901, 12.00166891, 12.22821773, 12.49130697,
       12.08619295, 12.22671647, 12.56654994, 11.85890753, 12.2294377 ,
       12.01835645, 11.96199913, 12.44919346, 11.9773974 , 12.0510052 ,
       10.69185928, 11.70847801, 11.90134516, 11.87014744, 12.19840116,
       11.63964693, 11.61413355, 11.64133324, 11.6157394 , 12.6820744 ,
       11.86807418, 11.87269624, 12.10036352, 12.12199539, 12.15189601,
       11.75546841, 12.34487638, 11.73925117, 11.93369128, 12.13304241,
       12.16826235, 12.77759975, 12.15821661, 11.72114969, 10.73477537,
       12.83914901, 12.829333  , 11.76512986, 12.38223899, 13.5899571 ,
       12.80237905, 11.76486084, 12.00519295, 12.07270465, 11.77857798,
       11.7490965 , 12.31102572, 12.16573959, 11.75508023, 11.18043278,
       11.74036726, 11.87421861, 12.53749634, 11.94713577, 11.3124608 ,
       11.6710168 , 11.88588948, 11.77626194, 11.42946453, 11.80927745,
       12.17538618, 11.74258589, 12.63067915, 11.86756221, 11.62585114,
       11.68105294, 12.3902873 , 12.70459607, 13.11718269, 12.28475964,
       12.86518872, 11.52673292, 11.72756873, 11.8466619 , 12.66532954,
       11.65510651, 11.65917166, 12.25038767, 11.72963153, 11.98581209,
       12.14719559, 11.22136867, 11.78621748, 11.87777951, 12.43755028,
       11.94546165, 12.54813703, 12.36249929, 12.17471981, 11.38191613,
       11.68068887, 11.41856492, 11.87298762, 11.85168345, 12.16139195,
       12.08396804, 12.22331042, 11.03593138, 12.18745513, 11.7905806 ,
       12.34521259, 12.2393992 , 11.60687468, 12.64960312, 12.17977446,
       11.7798295 , 12.31878867, 11.82252486, 11.84374228, 11.61677552,
       12.31324801, 11.92067065, 11.64210458, 12.04918829,  9.57025099,
       12.45341233, 12.25936784, 11.902251  , 11.6762442 , 11.74219546,
       11.77915593, 12.24495595, 12.28754267, 11.45057589, 12.2953783 ,
       11.83246315, 11.1116299 , 11.54101819, 12.02622275, 11.16033757,
       11.53876551, 12.0525782 , 11.6268128 , 11.8011384 , 12.24769102,
       11.81536656, 12.1896768 , 11.98273113, 12.32519276, 11.65296609,
       11.5726394 , 12.61636157, 12.34312084, 13.10265477, 12.13016412,
       11.78417726, 11.89322674, 12.03884574, 11.77153301, 11.43043134,
       12.1092593 , 12.0011776 , 11.81943923, 11.49459078, 11.83338156,
       11.87602724, 11.66222664, 11.67852533, 12.02806379, 12.43211527,
       12.62152434, 12.13925446, 11.74578044, 12.35022125, 12.71612851,
       12.30019546, 11.97012556, 11.80701495, 11.61750543, 12.07998393,
       12.97875415, 12.30810327, 12.35727966, 11.34959558, 11.46932227,
       11.87931994, 11.86451597, 12.57285115, 12.27915029, 11.77461936,
       12.24966304, 11.3204711 , 12.22080631, 11.60973301, 12.57945419,
       12.03605827, 12.29303475, 11.84782627, 12.44397922, 12.11088653,
       11.72390676, 11.6644749 ])

In [77]:
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [80]:
mae = mean_absolute_error(y_test,y_pred_log)
mse = mean_squared_error(y_test,y_pred_log)
r = r2_score(y_test,y_pred_log)

print(f"Mean absolute error : {mae:.2f}")
print(f"Mean Squared Error : {mse:.2f}")
print(f"r2 : {r:.2f}")

Mean absolute error : 16342.42
Mean Squared Error : 698735372.30
r2 : 0.91

In [82]:
test_predictions = model.predict(y_encoded)

test_predictions = np.where(test_predictions < 0, 0, test_predictions)

# Convert to integer prices
test_predictions = np.round(test_predictions, 0).astype(int)  

submission = pd.DataFrame({'Id':y_encoded.index , 'SalePrice':test_predictions})

submission.to_csv("submission.csv",index =False)